### ISSUE TITLE
theme: "dark" poperty does not work

### ISSUE THREAD

**Issue by lukmayer** [parmsam/quarto-excalidraw#3]
Hi there,

The theme property for excalidraw does not appear to be working.

Minimally reproducible example:

```
---
title: "test"
format: 
  revealjs:
    excalidraw:
      theme: "dark"

revealjs-plugins:
  - excalidraw
---
```

Expected behavior: Excalidraw opens in Dark Mode

Actual behavior: Excalidraw opens in Light Mode

Dark Mode can be manually activated through the menu, but this is  a bit tedious.

Quarto: 1.6.42
quarto-excalidraw: 1.3.0

Many thanks for your efforts!
